/* Khongchat demo data.
   Places and events are real. Coordinates are approximate.
   Listings are real, from public sources (see the note above them). Crafts are real; the passport reward and codes are demo.
   Event dates vary each year: confirm with Manipur Tourism before publishing. */

window.KC_DATA = {
  interests: [
    { id: "heritage", label: "Heritage" },
    { id: "nature", label: "Nature" },
    { id: "culture", label: "Culture" },
    { id: "food", label: "Food" },
    { id: "adventure", label: "Adventure" },
    { id: "shopping", label: "Crafts and shopping" },
    { id: "sports", label: "Sports" }
  ],

  regions: {
    imphal: "Imphal city",
    loktak: "Loktak and Moirang",
    east: "Thoubal, Kakching and Andro",
    ukhrul: "Ukhrul",
    senapati: "Senapati and Mao",
    tamenglong: "Tamenglong",
    churachandpur: "Churachandpur"
  },

  places: [
    { id: "kangla", name: "Kangla Fort", region: "imphal", lat: 24.808, lon: 93.942, tags: ["heritage", "culture"], hours: "9 AM to 4 PM",
      blurb: "Seat of the Meitei kings for centuries, on the banks of the Imphal river.", tip: "Go before 10 AM for the quiet grounds." },
    { id: "govindajee", name: "Shree Govindajee Temple", region: "imphal", lat: 24.806, lon: 93.945, tags: ["heritage", "culture"], hours: "Dawn to dusk",
      blurb: "Vaishnavite temple beside the old palace, with twin gold domes.", tip: "Evening aarti is the time to visit." },
    { id: "imakeithel", name: "Ima Keithel", region: "imphal", lat: 24.808, lon: 93.937, tags: ["food", "shopping", "culture"], hours: "Morning to 4 PM",
      blurb: "A market run entirely by women, trading for generations.", tip: "Try eromba and singju. Carry cash." },
    { id: "museum", name: "Manipur State Museum", region: "imphal", lat: 24.806, lon: 93.938, tags: ["heritage", "culture"], hours: "10 AM to 4 PM, closed Mondays",
      blurb: "Textiles, royal boats and tribal collections from across the state.", tip: "Look for the royal hiyang hiren boat." },
    { id: "warcemetery", name: "Imphal War Cemetery", region: "imphal", lat: 24.826, lon: 93.940, tags: ["heritage"], hours: "8 AM to 4 PM",
      blurb: "Commonwealth graves from the 1944 Battle of Imphal.", tip: "Quiet and well kept. Short visit." },
    { id: "marjing", name: "Marjing Polo Statue", region: "imphal", lat: 24.830, lon: 94.020, tags: ["sports", "heritage"], hours: "Open all day",
      blurb: "A giant polo rider on a Manipuri pony. Manipur is the home of modern polo.", tip: "Best at sunset, views over the valley." },
    { id: "sendra", name: "Sendra, Loktak Lake", region: "loktak", lat: 24.525, lon: 93.800, tags: ["nature"], hours: "Daytime",
      blurb: "Largest freshwater lake in the Northeast, dotted with floating phumdis.", tip: "Take a boat out in the late afternoon." },
    { id: "keibul", name: "Keibul Lamjao National Park", region: "loktak", lat: 24.490, lon: 93.820, tags: ["nature"], hours: "Early morning best",
      blurb: "The world's only floating national park, home of the sangai deer.", tip: "Sangai are most active at dawn." },
    { id: "ina", name: "INA Memorial, Moirang", region: "loktak", lat: 24.499, lon: 93.776, tags: ["heritage"], hours: "10 AM to 4 PM",
      blurb: "Where the Indian National Army raised the tricolour in 1944.", tip: "Pair it with Loktak the same day." },
    { id: "takmu", name: "Takmu Water Sports Complex", region: "loktak", lat: 24.520, lon: 93.790, tags: ["adventure", "nature"], hours: "Daytime, weather permitting",
      blurb: "Kayaking and boating on Loktak.", tip: "Check operating status before you go." },
    { id: "andro", name: "Andro village", region: "east", lat: 24.767, lon: 94.050, tags: ["culture", "shopping", "heritage"], hours: "Daytime",
      blurb: "Ancient village known for hand-built black pottery and a living cultural complex.", tip: "Buy direct from the potters." },
    { id: "khongjom", name: "Khongjom War Memorial", region: "east", lat: 24.450, lon: 94.030, tags: ["heritage"], hours: "Daytime",
      blurb: "Marks the 1891 Anglo-Manipur war. Remembered every April on Khongjom Day.", tip: "Climb the hillock for the view." },
    { id: "kakching", name: "Kakching Garden", region: "east", lat: 24.490, lon: 93.985, tags: ["nature"], hours: "9 AM to 5 PM",
      blurb: "Hillside garden with walking trails and views over Kakching town.", tip: "Good family stop." },
    { id: "zoo", name: "Manipur Zoological Garden", region: "imphal", lat: 24.800, lon: 93.890, tags: ["nature"], hours: "9 AM to 4 PM, closed Mondays",
      blurb: "At Iroisemba, at the foot of the western hills. The easiest place to see the sangai deer.", tip: "Good if you cannot make dawn at Keibul Lamjao." },
    { id: "bishnupur", name: "Vishnu Temple, Bishnupur", region: "loktak", lat: 24.630, lon: 93.770, tags: ["heritage"], hours: "Daytime",
      blurb: "A small brick temple from the 15th century, with a Chinese-style roof.", tip: "It sits on the road to Moirang. Stop on the way." },
    { id: "shirui", name: "Shirui Hills, Ukhrul", region: "ukhrul", lat: 25.100, lon: 94.450, tags: ["nature", "adventure"], hours: "Daytime trek",
      blurb: "Home of the Shirui lily, which blooms nowhere else.", tip: "Lily season is around May." },
    { id: "khangkhui", name: "Khangkhui Cave", region: "ukhrul", lat: 25.050, lon: 94.380, tags: ["nature", "adventure", "heritage"], hours: "Daytime",
      blurb: "Limestone cave near Ukhrul town, used as a shelter by villagers in the Second World War.", tip: "Carry a torch and wear shoes with grip." },
    { id: "dzuko", name: "Dzuko Valley", region: "senapati", lat: 25.550, lon: 94.070, tags: ["nature", "adventure"], hours: "Overnight trek",
      blurb: "High valley on the Manipur and Nagaland border, carpeted with flowers in season.", tip: "Go with a local guide." },
    { id: "makhel", name: "Makhel", region: "senapati", lat: 25.470, lon: 94.090, tags: ["heritage", "culture"], hours: "Daytime",
      blurb: "Mao Naga village honoured as a place of origin by many Naga peoples, with its ancestral stones.", tip: "Ask the village council before taking photos." },
    { id: "zeilad", name: "Zeilad Lake", region: "tamenglong", lat: 24.880, lon: 93.450, tags: ["nature"], hours: "Daytime",
      blurb: "A cluster of quiet lakes in the Zeliangrong Naga hills, rich in birds.", tip: "Mornings are clear before the mist rolls in." },
    { id: "tharon", name: "Tharon Cave", region: "tamenglong", lat: 24.930, lon: 93.520, tags: ["adventure", "heritage"], hours: "Daytime, with a guide",
      blurb: "Long cave system near Tharon village, with signs of ancient settlement.", tip: "Hire a guide from the village." },
    { id: "khuga", name: "Khuga Dam", region: "churachandpur", lat: 24.270, lon: 93.660, tags: ["nature"], hours: "Daytime",
      blurb: "Reservoir in the southern hills, with green slopes and a long walk along the dam.", tip: "Check local advisories before you travel." }
  ],

  /* Manipur state boundary, [lat, lon]. From Natural Earth 1:10m admin-1 (public domain),
     simplified to 114 points so it precaches and draws offline. */
  outline: [
    [25.447, 94.650], [25.395, 94.608], [25.245, 94.550], [25.204, 94.553], [25.174, 94.577], [25.139, 94.689],
    [25.110, 94.707], [25.068, 94.714], [25.026, 94.709], [24.975, 94.674], [24.889, 94.655], [24.813, 94.599],
    [24.730, 94.582], [24.709, 94.556], [24.705, 94.516], [24.597, 94.475], [24.560, 94.418], [24.495, 94.397],
    [24.466, 94.364], [24.425, 94.361], [24.394, 94.329], [24.363, 94.331], [24.333, 94.295], [24.266, 94.283],
    [24.160, 94.234], [23.995, 94.190], [23.919, 94.135], [23.857, 94.132], [23.842, 94.117], [23.843, 94.100],
    [23.888, 94.055], [23.917, 93.998], [23.945, 93.883], [23.936, 93.804], [23.945, 93.783], [23.995, 93.743],
    [24.005, 93.711], [24.009, 93.612], [23.995, 93.588], [23.968, 93.571], [23.966, 93.561], [23.981, 93.543],
    [23.959, 93.496], [23.960, 93.457], [23.995, 93.439], [24.078, 93.368], [24.089, 93.349], [24.080, 93.322],
    [24.036, 93.303], [24.018, 93.249], [24.049, 93.252], [24.069, 93.233], [24.049, 93.213], [24.040, 93.187],
    [24.041, 93.173], [24.055, 93.168], [24.062, 93.148], [24.045, 93.106], [24.072, 93.071], [24.105, 92.979],
    [24.131, 92.998], [24.240, 93.018], [24.274, 93.014], [24.327, 93.046], [24.354, 93.023], [24.413, 93.012],
    [24.415, 93.037], [24.559, 93.065], [24.577, 93.101], [24.624, 93.080], [24.672, 93.106], [24.683, 93.091],
    [24.707, 93.087], [24.797, 93.118], [24.824, 93.148], [24.809, 93.181], [24.817, 93.199], [24.848, 93.207],
    [24.915, 93.253], [24.945, 93.239], [24.973, 93.277], [25.009, 93.260], [25.036, 93.263], [25.056, 93.281],
    [25.066, 93.312], [25.235, 93.394], [25.302, 93.449], [25.260, 93.515], [25.248, 93.558], [25.213, 93.586],
    [25.206, 93.605], [25.262, 93.649], [25.314, 93.679], [25.328, 93.679], [25.446, 93.809], [25.480, 93.808],
    [25.500, 93.759], [25.532, 93.770], [25.544, 93.803], [25.554, 93.930], [25.554, 94.027], [25.520, 94.084],
    [25.521, 94.151], [25.497, 94.195], [25.512, 94.325], [25.541, 94.387], [25.594, 94.435], [25.624, 94.490],
    [25.688, 94.570], [25.621, 94.571], [25.514, 94.536], [25.490, 94.553], [25.461, 94.600], [25.447, 94.650]
  ],

  /* Loktak Lake shoreline, [lat, lon]. From OpenStreetMap (relation 9207024), ODbL,
     simplified to 74 points. Credit: (c) OpenStreetMap contributors. */
  loktak: [
    [24.5961, 93.8039], [24.5898, 93.8046], [24.5854, 93.8104], [24.5900, 93.8064], [24.5944, 93.8068],
    [24.6069, 93.8194], [24.6033, 93.8249], [24.5906, 93.8299], [24.5912, 93.8443], [24.5879, 93.8479],
    [24.5873, 93.8558], [24.5834, 93.8598], [24.5753, 93.8558], [24.5712, 93.8479], [24.5676, 93.8474],
    [24.5516, 93.8608], [24.5499, 93.8555], [24.5346, 93.8555], [24.5291, 93.8524], [24.5268, 93.8606],
    [24.5238, 93.8614], [24.5195, 93.8602], [24.5194, 93.8539], [24.5172, 93.8527], [24.5123, 93.8605],
    [24.5045, 93.8557], [24.5056, 93.8496], [24.5097, 93.8507], [24.5163, 93.8460], [24.5156, 93.8434],
    [24.5081, 93.8406], [24.5063, 93.8361], [24.5105, 93.8306], [24.5136, 93.8304], [24.5148, 93.8193],
    [24.5194, 93.8170], [24.5206, 93.8198], [24.5245, 93.8169], [24.5258, 93.8206], [24.5290, 93.8193],
    [24.5209, 93.8114], [24.5251, 93.8021], [24.5114, 93.7877], [24.5110, 93.7773], [24.5142, 93.7700],
    [24.5229, 93.7637], [24.5340, 93.7638], [24.5447, 93.7705], [24.5518, 93.7721], [24.5548, 93.7697],
    [24.5593, 93.7702], [24.5650, 93.7726], [24.5636, 93.7764], [24.5675, 93.7770], [24.5687, 93.7818],
    [24.5765, 93.7790], [24.5782, 93.7747], [24.5801, 93.7754], [24.5785, 93.7838], [24.5807, 93.7854],
    [24.5845, 93.7820], [24.5858, 93.7874], [24.5880, 93.7872], [24.5915, 93.7918], [24.5940, 93.7888],
    [24.5952, 93.7899], [24.5933, 93.7972], [24.5947, 93.8023], [24.6005, 93.7988], [24.6139, 93.8062],
    [24.6073, 93.8097], [24.6062, 93.8057], [24.5977, 93.8067], [24.5961, 93.8039]
  ],

  /* months: 0-11, approximate. Most follow the lunar calendar, so dates move each year. */
  events: [
    { name: "Manipur Sangai Festival", who: "Statewide", months: [10], when: "November, annually", place: "Imphal and venues statewide", tags: ["culture", "food", "shopping"],
      blurb: "The state's biggest tourism festival: dance, crafts, food and polo." },
    { name: "Yaoshang", who: "Meitei", months: [1, 2], when: "February or March, full moon", place: "Across the valley", tags: ["culture", "sports"],
      blurb: "Five days of Thabal Chongba folk dance and sports." },
    { name: "Cheiraoba", who: "Meitei", months: [2, 3], when: "March or April, Sajibu month", place: "Across the valley", tags: ["culture", "food"],
      blurb: "Meitei new year. Families cook a feast, then climb a nearby hill for luck in the year ahead." },
    { name: "Lai Haraoba", who: "Meitei", months: [3, 4], when: "April to May", place: "Village shrines", tags: ["culture", "heritage"],
      blurb: "Ritual festival of the Umang Lai forest deities." },
    { name: "Kang", who: "Meitei", months: [5, 6], when: "June or July", place: "Shree Govindajee Temple and neighbourhoods", tags: ["culture", "heritage"],
      blurb: "The Manipuri chariot festival. Nights of Thabal Chongba in every locality." },
    { name: "Heikru Hidongba", who: "Meitei", months: [8], when: "September", place: "Bijoy Govinda, Imphal", tags: ["culture", "sports", "heritage"],
      blurb: "Royal boat race on the palace moat, with long dragon-headed boats." },
    { name: "Mera Houchongba", who: "Meitei, Naga and Kuki", months: [9], when: "October, Mera month", place: "Kangla Fort", tags: ["culture", "heritage"],
      blurb: "Hill and valley peoples meet at Kangla to exchange gifts, an old festival of unity." },
    { name: "Ningol Chakouba", who: "Meitei", months: [9, 10], when: "October or November", place: "Homes across the valley", tags: ["food", "culture"],
      blurb: "Married daughters return home for a family feast and gifts." },
    { name: "Ras Leela", who: "Meitei", months: [10], when: "Kartik full moon, November", place: "Shree Govindajee Temple", tags: ["culture", "heritage"],
      blurb: "All-night Manipuri classical dance of Krishna and the gopis." },
    { name: "Emoinu Eratpa", who: "Meitei", months: [11, 0], when: "December or January", place: "Homes across the valley", tags: ["culture", "food"],
      blurb: "Honours Emoinu, goddess of wealth and the home, with a quiet evening offering." },
    { name: "Lui-Ngai-Ni", who: "Naga", months: [1], when: "15 February", place: "Naga villages, host district rotates", tags: ["culture"],
      blurb: "Seed-sowing festival shared by the Naga peoples of Manipur. Dance, song and full dress." },
    { name: "Luira Phanit", who: "Tangkhul Naga", months: [1, 2], when: "February or March", place: "Ukhrul", tags: ["culture"],
      blurb: "The Tangkhul seed-sowing festival that opens the farming year." },
    { name: "Shirui Lily Festival", who: "Tangkhul Naga", months: [4], when: "Around May", place: "Ukhrul", tags: ["nature", "culture"],
      blurb: "Celebrates the lily found only on Shirui hills." },
    { name: "Kut", who: "Kuki-Chin-Mizo", months: [10], when: "1 November", place: "Across the state", tags: ["culture"],
      blurb: "Post-harvest festival of the Kuki-Chin-Mizo communities." },
    { name: "Chumpha", who: "Tangkhul Naga", months: [11], when: "December", place: "Ukhrul", tags: ["culture", "food"],
      blurb: "Tangkhul post-harvest festival. A time of feasting and thanks." },
    { name: "Gaan-Ngai", who: "Zeliangrong Naga", months: [11, 0], when: "December or January", place: "Tamenglong and Imphal", tags: ["culture", "heritage"],
      blurb: "Five-day post-harvest festival of the Zeliangrong people, with sacred fire and dance." },
    { name: "Tamenglong Orange Festival", who: "Statewide", months: [11, 0], when: "December or January", place: "Tamenglong", tags: ["food", "shopping"],
      blurb: "The hill district's famous oranges, with a farmers' market and local food." }
  ],

  /* REAL LISTINGS, researched 22 Sep 2026 from public sources.
     level: "govt"      = listed on a Government of Manipur / India website
            "business"  = published by the business on its own website
            "directory" = travel guide or directory; call to confirm
     Prices are indicative, as published on the date checked. Contacts are only those the business or govt published. */
  listings: [
    /* ---------- STAY ---------- */
    { type: "stay", name: "Sendra Park and Resort", region: "loktak", area: "Sendra hills, above Loktak Lake, about 30 km from Imphal",
      note: "Deluxe rooms and eco cottages. Sangai Cafe on site. Keibul Lamjao visits arranged with notice.",
      price: "Deluxe from Rs 4,400 single, Rs 4,950 double. Cottage Rs 7,499. Plus GST. Tariff valid Apr 2026 to Mar 2027.",
      phone: "+91 81319 80420", email: "reservation@theclassichotel.in",
      level: "business", source: { label: "Classic Group of Hotels", url: "https://www.classicgroupofhotels.com/sendra-resort/" } },
    { type: "stay", name: "Maipakchao Family Home Stay", region: "loktak", area: "Thanga island, Loktak Lake, near Moirang",
      note: "Family-run. Simple rooms with private toilet. Boat rides, go out with local fishermen.",
      price: "Rs 1,200 per person per night, meals included.",
      web: "https://www.facebook.com/Maipakchao-family-stay-loktak-Manipur-394953554281803/",
      level: "directory", source: { label: "Responsible Tourism India", url: "https://www.responsibletourismindia.com/stay/maipakchao-family-home-stay/318" } },
    { type: "stay", name: "Loktak Aqua Inn floating homestay", region: "loktak", area: "Thanga Karang, Loktak Lake",
      note: "Eco floating huts on the phumdis.",
      price: "Around Rs 4,032 per night.",
      phone: "+91 96125 93606",
      level: "directory", source: { label: "Wikivoyage", url: "https://en.wikivoyage.org/wiki/Floating_restaurants_and_homestays_in_the_Loktak_Lake" } },
    { type: "stay", name: "Hotel Imphal", region: "imphal", area: "North AOC, Imphal",
      note: "Central hotel run by the Classic Group. Near the Directorate of Tourism.",
      price: "Tariff on request.",
      phone: "0385 242 2840", email: "imphalreservation@theclassichotel.in",
      level: "business", source: { label: "hotelimphal.com", url: "https://www.hotelimphal.com/restaurant/" } },
    { type: "stay", name: "Hearth of Imphal", region: "imphal", area: "About 8 km from Imphal airport",
      note: "Homestay.",
      price: "From Rs 1,800 per night.",
      phone: "+91 70855 93415",
      level: "directory", source: { label: "WanderOn", url: "https://wanderon.in/blogs/homestays-in-imphal" } },
    { type: "stay", name: "Hotel Tip Top", region: "ukhrul", area: "Phungreitang, Ukhrul",
      note: "Base for Shirui Hills.", price: "Tariff on request.",
      phone: "+91 98627 16098",
      level: "govt", source: { label: "Ukhrul District, Govt of Manipur", url: "https://ukhrul.nic.in/accommodation/" } },
    { type: "stay", name: "Kopa's Eatery and Lodging", region: "ukhrul", area: "Phungreitang, opposite ZEO office, Ukhrul",
      note: "Rooms and a kitchen in town.", price: "Tariff on request.",
      phone: "+91 82599 22827",
      level: "govt", source: { label: "Ukhrul District, Govt of Manipur", url: "https://ukhrul.nic.in/accommodation/" } },

    /* ---------- EAT ---------- */
    { type: "eat", name: "Luxmi Kitchen", region: "imphal", area: "Wahengbam Leikai Road, Sagolband, Imphal",
      note: "Manipuri thali with 13 or more dishes. Try sana thongba.",
      price: "Price not published. Call to confirm.",
      phone: "0385 244 0885",
      level: "directory", source: { label: "WanderOn", url: "https://wanderon.in/blogs/places-to-eat-in-imphal" } },
    { type: "eat", name: "Hotel Imoinu", region: "imphal", area: "Imphal",
      note: "Veg and non-veg Manipuri thali. Fish thali. Open 24 hours.",
      price: "About Rs 400 for two.",
      level: "directory", source: { label: "WanderOn", url: "https://wanderon.in/blogs/places-to-eat-in-imphal" } },
    { type: "eat", name: "Imphal Cafe, Hotel Imphal", region: "imphal", area: "North AOC, Imphal",
      note: "Indian, Chinese and continental. Breakfast 6:30 to 10, lunch 12 to 3, dinner 6 to 9:30.",
      price: "Price not published.",
      phone: "0385 242 2840", email: "fnbimphal@theclassichotel.in",
      level: "business", source: { label: "hotelimphal.com", url: "https://www.hotelimphal.com/restaurant/" } },
    { type: "eat", name: "Loktak Heritage Floating Hut", region: "loktak", area: "Thanga, Loktak Lake",
      note: "Multi-storey floating house. Fish and vegetarian food.",
      price: "Price not published.",
      phone: "+91 81198 63210",
      level: "directory", source: { label: "Wikivoyage", url: "https://en.wikivoyage.org/wiki/Floating_restaurants_and_homestays_in_the_Loktak_Lake" } },
    { type: "eat", name: "Sangai Cafe, Sendra", region: "loktak", area: "Sendra Park and Resort",
      note: "Indian, Chinese and local food with a view over Loktak.",
      price: "Price not published.",
      phone: "+91 81319 80420",
      level: "business", source: { label: "Classic Group of Hotels", url: "https://www.classicgroupofhotels.com/sendra-resort/" } },

    /* ---------- GUIDES (tour operators listed by Imphal West district) ---------- */
    { type: "guide", name: "Directorate of Tourism, Manipur", region: "imphal", area: "North AOC, Imphal West",
      note: "Ask here for government-registered tourist guides.",
      price: "Free to ask.",
      phone: "0385 242 1794", email: "mtqueries@gmail.com",
      level: "govt", source: { label: "Manipur Tourism", url: "https://manipurtourism.gov.in/contact-us/" } },
    { type: "guide", name: "Classic Tours and Travels", region: "imphal", area: "North AOC, Imphal West",
      note: "Day tours to custom tours.", price: "Packages on request.",
      phone: "+91 81319 80420", email: "travels@theclassichotel.in",
      level: "govt", source: { label: "Imphal West District, Govt of Manipur", url: "https://imphalwest.nic.in/tourist-packages/" } },
    { type: "guide", name: "Shija Tours and Travels", region: "imphal", area: "Meitei Langol, Lamphelpat, Imphal",
      note: "Day tours to custom tours.", price: "Packages on request.",
      phone: "+91 94026 99699", email: "shijatoursandtravels@gmail.com",
      level: "govt", source: { label: "Imphal West District, Govt of Manipur", url: "https://imphalwest.nic.in/tourist-packages/" } },
    { type: "guide", name: "Seven Sister Holidays", region: "imphal", area: "M G Avenue, Imphal",
      note: "Day tours to custom tours.", price: "Packages on request.",
      phone: "0385 244 3977",
      level: "govt", source: { label: "Imphal West District, Govt of Manipur", url: "https://imphalwest.nic.in/tourist-packages/" } },
    { type: "guide", name: "KB Enterprises", region: "imphal", area: "Imphal",
      note: "Tour operator.", price: "Packages on request.",
      phone: "+91 98620 28656", email: "kbentp@gmail.com",
      level: "govt", source: { label: "Imphal West District, Govt of Manipur", url: "https://imphalwest.nic.in/tourist-packages/" } },

    /* ---------- CRAFTS ---------- */
    { type: "craft", name: "Khwairamband Ima Keithel", region: "imphal", area: "Khwairamband Bazaar, Imphal",
      note: "About 3,000 women vendors. Handloom shawls, crafts, jewellery.",
      price: "Bargaining is normal.",
      level: "govt", source: { label: "Incredible India", url: "https://www.incredibleindia.gov.in/en/manipur/imphal/the-captivating-world-of-shopping-in-imphal" } },
    { type: "craft", name: "MHHDC sales emporium", region: "imphal", area: "Paona Bazaar, Imphal",
      note: "Manipur Handlooms and Handicrafts Development Corporation shop. Silk, handwoven shawls, bamboo work.",
      price: "Government shop.",
      level: "govt", source: { label: "Incredible India", url: "https://www.incredibleindia.gov.in/en/manipur/imphal/the-captivating-world-of-shopping-in-imphal" } },
    { type: "craft", name: "GM Hall", region: "imphal", area: "Central Imphal",
      note: "Handlooms, toys, shawls and handicrafts.",
      price: "Fixed prices.",
      level: "govt", source: { label: "Incredible India", url: "https://www.incredibleindia.gov.in/en/manipur/imphal/the-captivating-world-of-shopping-in-imphal" } },
    { type: "craft", name: "Andro village and Mutua Bahadur Museum", region: "east", area: "Andro, about 21 km from Imphal",
      note: "Coil pottery village. Museum of pottery, manuscripts, bell metal and tribal houses.",
      price: "Check at the gate.",
      level: "govt", source: { label: "Imphal East District, Govt of Manipur", url: "https://imphaleast.nic.in/tourist-place/mutua_bahadur/" } },
    { type: "craft", name: "Longpi (Nungbi) black pottery", region: "ukhrul", area: "Nungbi, 38 km from Ukhrul on NH150",
      note: "Tangkhul black stone pottery made without a wheel. Cookers, kettles, cups.",
      price: "Buy direct from potters.",
      level: "govt", source: { label: "Ukhrul District, Govt of Manipur", url: "https://ukhrul.nic.in/tourist-place/nungbi-pottery/" } },

    /* ---------- GETTING THERE ---------- */
    { type: "move", name: "Imphal Airport to city", region: "imphal", note: "About 8 km. Prepaid taxis at arrivals." },
    { type: "move", name: "Imphal to Moirang and Loktak", region: "loktak", note: "About 45 km by road. Shared taxis from Imphal." }
  ],
  checked: "22 Sep 2026",
  levels: { govt: "Govt listed", business: "Business website", directory: "Travel guide, call to confirm" },

  /* Craft passport. Crafts, villages and GI tags are real. Keep ids stable: QR codes point at #/stamp/<id>.
     listing is the name of a row in listings above (where to buy). */
  crafts: [
    { id: "andro", name: "Andro coil pottery", craft: "Pottery", region: "east",
      where: "Andro village, about 21 km from Imphal", gi: false,
      about: "Coil-built pottery made without a wheel. The village also has the Mutua Bahadur museum.",
      listing: "Andro village and Mutua Bahadur Museum" },
    { id: "longpi", name: "Longpi black pottery", craft: "Pottery", region: "ukhrul",
      where: "Nungbi, 38 km from Ukhrul on NH150", gi: true,
      about: "Tangkhul black stone pottery, shaped by hand and stone, no wheel.",
      listing: "Longpi (Nungbi) black pottery" },
    { id: "imakeithel", name: "Ima Keithel handloom", craft: "Handloom", region: "imphal",
      where: "Khwairamband Bazaar, Imphal", gi: false,
      about: "About 3,000 women vendors. Phanek, shawls and everyday handloom.",
      listing: "Khwairamband Ima Keithel" },
    { id: "moirangphee", name: "Moirang Phee weaving", craft: "Handloom", region: "loktak",
      where: "Moirang and around Loktak", gi: true,
      about: "Temple-motif border woven into phanek and shawls. GI tagged.",
      listing: "MHHDC sales emporium" }
  ],
  unlock: { need: 3, reward: "Guided Andro village walk with a potter", note: "Demo reward. A live version would be agreed with the Tourism Department and the artisan group." },

  /* Saved with the trip so they work offline. */
  contacts: [
    { label: "Emergency (all India)", number: "112" },
    { label: "Tourist helpline, Ministry of Tourism", number: "1363" }
  ],
  ilp: [
    "Valid photo ID",
    "Passport-size photo",
    "Address proof",
    "Sponsor or host details",
    "Apply online, or at Imphal airport or the Mao and Jiribam gates"
  ],

  months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],

  sources: [
    { label: "Domestic visits: 139,500 (2022) to 58,000 (2023). Ministry of Tourism, via CEIC", url: "https://www.ceicdata.com/en/india/resident-visits-by-states/visitor-arrivals-local-manipur" },
    { label: "4,374 hours without internet in Manipur in 2023. SFLC.in, Let the Net Work 2.0 (via The Wire)", url: "https://m.thewire.in/article/government/internet-shutdown-manipur-haryana-bihar/amp" },
    { label: "Inner Line Permit portal, Government of Manipur", url: "https://manipurilponline.mn.gov.in/" }
  ]
};
/* Older code reads stamps: same array as crafts. */
window.KC_DATA.stamps = window.KC_DATA.crafts;
